const { spawnSync } = require('child_process');
const GIT = 'D:/development/Git/bin/git.exe';
const CWD = 'd:/project/_npm-wrap/vscode-config-installer';
const g = a => spawnSync(GIT, a, { encoding: 'utf8', cwd: CWD, windowsHide: true });
const r1 = g(['add', '-A']);
console.log(r1.stdout);
const r2 = g(['commit', '-m', 'fix(installer): detectEditorWindows 向上多层遍历，兼容非标准安装路径（如 Cursor/Kiro/Qoder 的 bin 在深层子目录）']);
console.log(r2.stdout || r2.stderr);
const r3 = g(['push']);
console.log(r3.stdout || r3.stderr);
