/*
 * ESLint Flat Config
 * @generated by @robot-admin/git-standards
 *
 * 直接修改此文件即可自定义 ESLint 规则
 */

import globals from 'globals';

export default [
  //MARK: 基础配置组
  {
    name: 'app/files-to-lint',
    files: ['**/*.{js,mjs}'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },

  {
    name: 'app/files-to-ignore',
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      '**/test/**',
    ],
  },

  //MARK: 核心规则组（按优先级排序）

  // 自定义规则组
  {
    rules: {
      //! 代码复杂度
      'max-depth': ['error', 4],
      complexity: ['warn', 15],

      //! 异步代码规范
      'no-await-in-loop': 'off',

      //MARK: 格式规范
      'no-irregular-whitespace': 'error',
      'no-multi-spaces': 'error',
      'space-infix-ops': 'error',
      'array-bracket-spacing': ['error', 'never'],
      'arrow-spacing': ['error', { before: true, after: true }],
      'max-params': ['warn', 6],
      'no-eval': 'error',
      'prefer-const': 'warn',
      'no-var': 'warn',
      'prefer-destructuring': [
        1,
        { object: true, array: false },
      ],
      'no-duplicate-imports': 'error',
    },
  },
];
